# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Please replace this file with
# cp -f /etc/nixos/hardware-configuration.nix ./host/hardware-configuration.nix
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  #####
  # This is the hardware configration generated by Nix installer
  #####
}